config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  scope "/candidatos" do
    get "/", to: "candidates#index"
    #get "/concursos-afins", to: "candidates#public_tenders"
    get "/:id/concursos", to: "candidates#public_tenders", as: :public_tenders
    get "/buscar", to: "candidates#search"
  end

  scope "/concursos" do
    get "/", to: "public_tenders#index"
    #get "/candidatos-afins", to: "public_tenders#candidates"
    get "/:id/candidatos", to: "public_tenders#candidates", as: :candidates
    get "/buscar", to: "public_tenders#search"
  end

  get '*path' => redirect('/')
end

app/models/candidate.rb
class Candidate
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::TagCollectible::Tagged

  field :name #Nome do Candidato
  field :document_number #CPF
  field :birthdate, type: Date #Data de Nascimento

  index({ document_number: 1 }, { unique: true })

  validates :name, presence: true
  validates :birthdate, presence: true
  validates :document_number, presence: true, uniqueness: true
  validate :validate_age
  validate :validate_document_number

  #Antes de ocorrer a validação, o método 'downcase_tags' é chamado, fazendo com que as tags, que neste caso representam as profissões dos candidatos, sejam transformadas em downcase, ou seja, minúsculas
  before_validation :downcase_tags

  private

  #Valida se o candidato é maior de 18 anos
  def validate_age
    if birthdate.present? && birthdate.to_date >= 18.years.ago.to_date
      errors.add(:birthdate, 'Candidato menor de idade.')
    end
  end

  #Valida o número do CPF informado
  def validate_document_number
    if not (document_number.present? && CPF.valid?(document_number))
      errors.add(:document_number, 'CPF inválido.')
    end
  end

  def downcase_tags
    tags = tags.map(&:downcase) if tags
  end

  #Função utilizada para retornar os candidatos, baseando-se na entrada de dados do usuário
  def self.search(params)
    #Varável do tipo array, onde os resultados da query seguinte serão armazenados, se houverem dados a armazenar
    results = Array.new
    #Query onde, os registros são buscados no banco de dados. As buscas são realizadas tanto pelo nome do Candidato, quanto pelo CPF
    candidates = any_of({:name => /.*#{params[:q].titleize}.*/ }, {document_number: /.*#{params[:q].gsub(".", "").gsub("-", "")}.*/}).only(:id, :name, :document_number)
    #Atribuição dos resultados da query no array declarado acima
    candidates.each do |candidate|
      #Foi utilizada a biblioteca Select2, que implementa o recurso 'Auto Complete'.
      #Os campos 'id' e 'text' são necessários para que o usuário escolha a opção correta e o sistema entanda a qual registro pertence a opção selecionada
      results << {
        id: candidate.id.to_s,
        text: candidate.name + " | " + candidate.document_number.gsub(/^(\d{3})(\d{3})(\d{3})(\d{2})/, "\\1.\\2.\\3-\\4")
      }
    end
    {results: results}
  end
end

app/models/public_tender.rb
class PublicTender
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::TagCollectible::Tagged

  field :department #Órgão
  field :document_number #Edital
  field :code #Código do Concurso

  validates :department, presence: true
  validates :document_number, presence: true
  validates :code, presence: true, uniqueness: true

  index({ code: 1 }, { unique: true })

  #Antes de ocorrer a validação, o método 'downcase_tags' é chamado, fazendo com que as tags, que neste caso representam as vagas do concurso, sejam transformadas em downcase, ou seja, minúsculas
  before_validation :downcase_tags

  def downcase_tags
    tags = tags.map(&:downcase) if tags
  end

  #Função utilizada para retornar os concursos públicos, baseando-se na entrada de dados do usuário
  def self.search(params)
    #Varável do tipo array, onde os resultados da query seguinte serão armazenados, se houverem dados a armazenar
    results = Array.new
    #Query onde, os registros são buscados no banco de dados. As buscas são realizadas tanto pelo nome do Órgão, quanto pelo código do concurso
    public_tenders = any_of({:department => /.*#{params[:q].upcase}.*/ }, {code: /.*#{params[:q]}.*/}).only(:id, :department, :code)
    #Atribuição dos resultados da query no array declarado acima
    public_tenders.each do |public_tender|
      #Foi utilizada a biblioteca Select2, que implementa o recurso 'Auto Complete'.
      #Os campos 'id' e 'text' são necessários para que o usuário escolha a opção correta e o sistema entanda a qual registro pertence a opção selecionada
      results << {
        id: public_tender.id.to_s,
        text: public_tender.department + " | " + public_tender.code
      }
    end
    {results: results}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    #Listando todos os candidatos, respeitando a páginação dos resultados
    @candidates = Candidate.asc("name").page(params[:page])
  end

  def public_tenders
    #Buscando o candidato pelo ID informado pelo usuário e listando todos os concurso à ele afins
    @candidate = Candidate.find(params[:id])
    @public_tenders = PublicTender.where(:tags.in => @candidate.tags).page(params[:page])
  end

  def search
    #Recebendo os paraâmetros da busca informados pelo usuário e executando as buscas
    render :json => Candidate.search(params)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index    
  end
end

app/controllers/public_tenders_controller.rb
class PublicTendersController < ApplicationController
  def index
    #Listando todos os concursos, respeitando a páginação dos resultados
    @public_tenders = PublicTender.asc("department").page(params[:page])
  end

  def candidates
    #Buscando o concursos pelo ID informado pelo usuário e listando todos os candidatos à ele afins
    @public_tender = PublicTender.find(params[:id])
    @candidates = Candidate.where(:tags.in => @public_tender.tags).page(params[:page])
  end

  def search
    #Recebendo os paraâmetros da busca informados pelo usuário e executando as buscas
    render :json => PublicTender.search(params), status: 200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/public_tenders_helper.rb
module PublicTendersHelper
end

app/views/candidates/index.html.erb
<div class="py-5 bg-light">
  <div class="container">
    <center>
      <form name="form-inline">
        <div class="form-group mb">
           <div class="col-md-6">
              <select id="search-box" class="form-control"></select>
           </div>
         </div>
       </form>
     </center>
    <div class="row">
      <h2>Candidatos</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Data de Nascimento</th>
            <th>Profissões</th>
          </tr>
        </thead>
        <tbody>
          <% @candidates.each do |candidate| %>
          <tr>
            <td><%= link_to candidate.name, public_tenders_path(candidate) %></td>
            <td><%= link_to candidate.document_number.gsub(/^(\d{3})(\d{3})(\d{3})(\d{2})/, "\\1.\\2.\\3-\\4"), public_tenders_path(candidate) %></td>
            <td><%= candidate.birthdate %></td>
            <td><%= candidate.tags %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <%= paginate @candidates, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/candidates/public_tenders.html.erb
<div class="py-5 bg-light">
  <div class="container">
      <center>
        <h2>Concursos Afins | Candidato: <%= @candidate.name %></h2>
        <p>CPF: <%= @candidate.document_number.gsub(/^(\d{3})(\d{3})(\d{3})(\d{2})/, "\\1.\\2.\\3-\\4") %> | Profissões: <%= @candidate.tags %></p>
      </center>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th>Órgão</th>
            <th>Edital</th>
            <th>Código do Concurso</th>
            <th>Lista de vagas</th>
          </tr>
        </thead>
        <tbody>
          <% @public_tenders.each do |public_tender| %>
          <tr>
            <td><%= link_to public_tender.department, candidates_path(public_tender) %></td>
            <td><%= public_tender.document_number %></td>
            <td><%= link_to public_tender.code, candidates_path(public_tender) %></td>
            <td><%= public_tender.tags %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <%= paginate @public_tenders, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Busca Vaga</h1>
      <p class="lead text-muted">Com o busca vaga, você poderá buscar vagas afins e todos os concursos abertos no ES</p>
      <p>
        <a href="/concursos" class="btn btn-primary my-2">Pesquisar concursos</a>
        <a href="/candidatos" class="btn btn-primary my-2">Pesquisar candidatos</a>
      </p>
    </div>
  </section>
</main>

app/views/layouts/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p>Busca vaga &copy; <%= DateTime.now.year %> | Dérick Hogan Pimenta</p>
    <p><a href="#" data-toggle="modal" data-target="#aboutModal">Sobre</a></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Busca vaga</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/concursos">Concursos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/candidatos">Candidatos</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_modals.html.erb
<div class="modal fade" id="aboutModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Sobre</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p>Projeto desenvolvido com o objetivo de pleitear uma bolsa de fomento para o desenvolvimento do projeto ES na Palma da Mão</p>
        <p>
          Foram utilizadas algumas das tecnologias mais modernas, disponíveis atualmente. Tais como:
          <ul>
            <li><strong>Linguagem/Framework</strong>: <%= link_to "Ruby on Rails", "https://rubyonrails.org/" %></li>
            <li><strong>Banco de Dados</strong>: <%= link_to "MongoDB", "https://www.mongodb.com/" %></li>
            <li><strong>Framework Web</strong>: <%= link_to "Bootstrap v4.1.1", "https://getbootstrap.com/" %></li>
            <li><strong>Servidor Web</strong>: <%= link_to "Puma", "https://puma.io/" %></li>
            <li><strong>Biblioteca de Testes</strong>: <%= link_to "RSpec", "https://rspec.info/" %></li>
            <li><strong>Biblioteca JavaScript</strong>: <%= link_to "JQuery", "https://jquery.com/" %></li>
            <li><strong>Hospedado em</strong>: <%= link_to "Heroku", "https://www.heroku.com/" %></li>
          </ul>
        </p>
        <p>Orgulhosamente desenvolvido no <%= link_to "Espírito Santo", "http://amores.es.gov.br/" %> por <%= link_to "Dérick Hogan Pimenta", "https://www.linkedin.com/in/derick-hogan-pimenta/" %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Busca Vaga | ESPM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
    <%= render partial: "layouts/footer" %>
    <%= render partial: "layouts/modals" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/public_tenders/candidates.html.erb
<div class="py-5 bg-light">
  <div class="container">
    <center>
      <h2>Candidatos Afins | Órgão: <%= @public_tender.department %></h2>
      <p>Edital: <%= @public_tender.document_number %> | Código do Concurso: <%= @public_tender.code %> | Lista de Vagas: <%= @public_tender.tags %></p>
    </center>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Data de Nascimento</th>
            <th>Profissões</th>
          </tr>
        </thead>
        <tbody>
          <% @candidates.each do |candidate| %>
          <tr>
            <td><%= link_to candidate.name, public_tenders_path(candidate) %></td>
            <td><%= link_to candidate.document_number.gsub(/^(\d{3})(\d{3})(\d{3})(\d{2})/, "\\1.\\2.\\3-\\4"), public_tenders_path(candidate) %></td>
            <td><%= candidate.birthdate %></td>
            <td><%= candidate.tags %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <%= paginate @candidates, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/public_tenders/index.html.erb
<div class="py-5 bg-light">
  <div class="container">
    <center>
      <form name="form-inline">
        <div class="form-group mb">
           <div class="col-md-6">
              <select id="search-box" class="form-control"></select>
           </div>
         </div>
       </form>
     </center>
    <div class="row">
      <h2>Concursos</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Órgão</th>
            <th>Edital</th>
            <th>Código do Concurso</th>
            <th>Lista de vagas</th>
          </tr>
        </thead>
        <tbody>
          <% @public_tenders.each do |public_tender| %>
          <tr>
            <td><%= link_to public_tender.department, candidates_path(public_tender) %></td>
            <td><%= public_tender.document_number %></td>
            <td><%= link_to public_tender.code, candidates_path(public_tender) %></td>
            <td><%= public_tender.tags %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <%= paginate @public_tenders, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>